global:
  scrape_interval: 5s # 默認抓取間隔

scrape_configs:
  - job_name: 'pm2-metrics'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:9209']
    fallback_scrape_protocol: PrometheusText0.0.4